# Site settings
title: Hyuga Blog
SEOTitle: 秦枫的博客 | Hyuga Blog
header-img: img/home/home-bg.jpg
email: hyuga0410@gmail.com
description: "每一次失败都通向成功."
keyword: "秦枫, hyuga0410, @hyuga0410, 秦枫的博客, Hyuga0410, 博客, 个人网站, 互联网, Web, 后端"
url: "http://hyuga.top"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/hyuga0410/hyuga0410.github.io.git" # you code repository

# Sidebar settings侧边栏
sidebar: true                           # 是否使用侧栏
sidebar-about-description: "Never give up.<br>谁的人生不曾迷茫？"
sidebar-avatar: /img/home/about-pic.jpg      # 使用绝对URL，看到它在' / '和' /about/ '



# SNS settings
RSS: false
# weibo_username:     hyuga0410
#zhihu_username:     hyuga0410
github_username:    hyuga0410
#facebook_username:  hyuga0410
#jianshu_username:   hyuga0410
#twitter_username:   hyuga0410




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 2c1cdc917ea312598d8e                            #生成的clientID
  clientSecret: 128abf3f41c71952c52d401c9a12967d9f96b10f    #生成的clientSecret
  repo: hyuga0410.github.io   #仓库名称
  owner: hyuga0410    #github用户名
  admin: hyuga0410
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-124165058-1'            # Format: UA-xxxxxx-xx
ga_domain: hyuga.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
{
  title: "屈定's Blog",
  href: "https://mrdear.cn/"
},{
  title: "Hollis",
  href: "http://www.hollischuang.com/"
}
]
